DEF rLCDC_BG_PRIORITY    EQU B_LCDC_BG
DEF rLCDC_SPRITES_ENABLE EQU B_LCDC_OBJS
DEF rLCDC_SPRITE_SIZE    EQU B_LCDC_OBJ_SIZE
DEF rLCDC_BG_TILEMAP     EQU B_LCDC_BG_MAP
DEF rLCDC_TILE_DATA      EQU B_LCDC_BLOCKS
DEF rLCDC_WINDOW_ENABLE  EQU B_LCDC_WINDOW
DEF rLCDC_WINDOW_TILEMAP EQU B_LCDC_WIN_MAP
DEF rLCDC_ENABLE EQU B_LCDC_ENABLE
DEF LEN_2BPP_TILE EQU TILE_SIZE
DEF LEN_1BPP_TILE EQU TILE_SIZE / 2
DEF TILE_1BPP_SIZE EQU TILE_SIZE / 2 ; bytes

DEF BG_MAP_WIDTH  EQU 32 ; tiles
DEF BG_MAP_HEIGHT EQU 32 ; tiles

DEF BLOCK_WIDTH EQU 4 ; tiles
DEF BLOCK_HEIGHT EQU BLOCK_WIDTH ; tiles
DEF SCREEN_BLOCK_WIDTH EQU 6 ; blocks
DEF SCREEN_BLOCK_HEIGHT EQU 5 ; blocks
DEF SURROUNDING_WIDTH  EQU SCREEN_BLOCK_WIDTH * BLOCK_WIDTH ; tiles
DEF SURROUNDING_HEIGHT EQU SCREEN_BLOCK_HEIGHT * BLOCK_HEIGHT ; tiles

DEF PIC_WIDTH  EQU 7 ; tiles
DEF PIC_HEIGHT EQU PIC_WIDTH ; tiles
DEF PIC_SIZE   EQU PIC_WIDTH * PIC_HEIGHT ; tiles

DEF SPRITEBUFFERSIZE EQU PIC_WIDTH * PIC_HEIGHT * TILE_1BPP_SIZE

; HP bar
DEF HP_BAR_GREEN  EQU 0
DEF HP_BAR_YELLOW EQU 1
DEF HP_BAR_RED    EQU 2

; hAutoBGTransferEnabled
DEF TRANSFERTOP    EQU 0
DEF TRANSFERMIDDLE EQU 1
DEF TRANSFERBOTTOM EQU 2

; hRedrawRowOrColumnMode
DEF REDRAW_COL EQU 1
DEF REDRAW_ROW EQU 2

; hUILayoutFlags
	const_def
	const BIT_PARTY_MENU_HP_BAR   ; 0
	const BIT_DOUBLE_SPACED_MENU  ; 1
	const BIT_SINGLE_SPACED_LINES ; 2

; tile list ids
; TileIDListPointerTable indexes (see data/tilemaps.asm)
	const_def
	const TILEMAP_MON_PIC
	const TILEMAP_SLIDE_DOWN_MON_PIC_7X5
	const TILEMAP_SLIDE_DOWN_MON_PIC_7X3
	const TILEMAP_GENGAR_INTRO_1
	const TILEMAP_GENGAR_INTRO_2
	const TILEMAP_GENGAR_INTRO_3
	const TILEMAP_GAME_BOY
	const TILEMAP_LINK_CABLE
DEF NUM_TILEMAPS EQU const_value

; Aliases for hardware_constants.asm names
DEF CGB                           EQU BOOTUP_A_CGB
DEF MBC1SRamEnable                EQU rRAMG
DEF MBC1RomBank                   EQU rROMB
DEF MBC1SRamBank                  EQU rRAMB
DEF MBC1SRamBankingMode           EQU rBMODE
DEF SRAM_ENABLE                   EQU RAMG_SRAM_ENABLE
DEF VBLANK                        EQU B_IF_VBLANK
DEF LCD_STAT                      EQU B_IF_STAT
DEF TIMER                         EQU B_IF_TIMER
DEF SERIAL                        EQU B_IF_SERIAL
DEF START_TRANSFER_EXTERNAL_CLOCK EQU $80
DEF START_TRANSFER_INTERNAL_CLOCK EQU $81
DEF rIE_VBLANK                    EQU B_IE_VBLANK
DEF rIE_LCD                       EQU B_IE_STAT
DEF rIE_TIMER                     EQU B_IE_TIMER
DEF rIE_SERIAL                    EQU B_IE_SERIAL
DEF rIE_JOYPAD                    EQU B_IE_JOYPAD
