#!/bin/bash
# Run from "gfx" folder

check_section() {
    local name="$1"
    shift
    local sum=0
    local missing=()
    echo "=== $name ==="
    for f in "$@"; do
        if [ -f "$f" ]; then
            size=$(stat -c "%s" "$f")
            sum=$((sum + size))
            printf "  %5d  %s\n" "$size" "$f"
        else
            missing+=("$f")
        fi
    done
    local headroom=$((16384 - sum))
    echo "  -----"
    echo "  Used:     $sum bytes ($(printf '0x%X' $sum))"
    echo "  Headroom: $headroom bytes"
    if [ ${#missing[@]} -gt 0 ]; then
        echo "  Missing files:"
        for f in "${missing[@]}"; do
            echo "    $f"
        done
    fi
    echo ""
}

check_section "Pics 1" \
  pokemon/front/rhydon.pic \
  pokemon/back_sw/rhydonb.pic \
  pokemon/front/kangaskhan.pic \
  pokemon/back_sw/kangaskhanb.pic \
  pokemon/front/spearow.pic \
  pokemon/back_sw/spearowb.pic \
  pokemon/back_sw/voltorbb.pic \
  pokemon/front_alt/voltorb.pic \
  pokemon/front/nidoking.pic \
  pokemon/back_sw/nidokingb.pic \
  pokemon/front/slowbro.pic \
  pokemon/back_sw/slowbrob.pic \
  pokemon/front/ivysaur.pic \
  pokemon/back_sw/ivysaurb.pic \
  pokemon/front/lickitung.pic \
  pokemon/back_sw/lickitungb.pic \
  pokemon/front/exeggcute.pic \
  pokemon/back_sw/exeggcuteb.pic \
  pokemon/front_alt/exeggcute.pic \
  pokemon/front/grimer.pic \
  pokemon/back_sw/grimerb.pic \
  pokemon/front/gengar.pic \
  pokemon/back_sw/gengarb.pic \
  pokemon/front_alt/gengar.pic \
  pokemon/front/nidoranf.pic \
  pokemon/back_sw/nidoranfb.pic \
  pokemon/front/nidoqueen.pic \
  pokemon/back_sw/nidoqueenb.pic \
  pokemon/front/cubone.pic \
  pokemon/back_sw/cuboneb.pic \
  pokemon/front/rhyhorn.pic \
  pokemon/back_sw/rhyhornb.pic \
  pokemon/front/lapras.pic \
  pokemon/back_sw/laprasb.pic \
  pokemon/front/arcanine.pic \
  pokemon/back_sw/arcanineb.pic \
  pokemon/front_alt/arcanine.pic \
  pokemon/front/gyarados.pic \
  pokemon/back_sw/gyaradosb.pic \
  pokemon/front/squirtle.pic \
  pokemon/back_sw/squirtleb.pic \
  pokemon/front_alt/squirtle.pic \
  pokemon/front/clefairy.pic \
  pokemon/back_sw/clefairyb.pic \
  pokemon/front/kakuna.pic \
  pokemon/back_sw/kakunab.pic \
  pokemon/back/machopb.pic

check_section "Pics 2" \
  pokemon/front/growlithe.pic \
  pokemon/back_sw/growlitheb.pic \
  pokemon/front/onix.pic \
  pokemon/back_sw/onixb.pic \
  pokemon/front_alt/onix.pic \
  pokemon/front/fearow.pic \
  pokemon/back_sw/fearowb.pic \
  pokemon/front/pidgey.pic \
  pokemon/back_sw/pidgeyb.pic \
  pokemon/front/slowpoke.pic \
  pokemon/back_sw/slowpokeb.pic \
  pokemon/front/kadabra.pic \
  pokemon/back_sw/kadabrab.pic \
  pokemon/front_alt/kadabra.pic \
  pokemon/front/graveler.pic \
  pokemon/back_sw/gravelerb.pic \
  pokemon/front_alt/graveler.pic \
  pokemon/front/chansey.pic \
  pokemon/back_sw/chanseyb.pic \
  pokemon/front/machoke.pic \
  pokemon/back_sw/machokeb.pic \
  pokemon/front/mr.mime.pic \
  pokemon/back_sw/mr.mimeb.pic \
  pokemon/front/hitmonlee.pic \
  pokemon/back_sw/hitmonleeb.pic \
  pokemon/front/arbok.pic \
  pokemon/back_sw/arbokb.pic \
  pokemon/front/parasect.pic \
  pokemon/back_sw/parasectb.pic \
  pokemon/front/psyduck.pic \
  pokemon/front/drowzee.pic \
  pokemon/back_sw/drowzeeb.pic \
  pokemon/front/golem.pic \
  pokemon/back_sw/golemb.pic \
  pokemon/front/magmar.pic \
  pokemon/back_sw/magmarb.pic \
  pokemon/front/electabuzz.pic \
  pokemon/back_sw/electabuzzb.pic \
  pokemon/front_alt/electabuzz.pic \
  pokemon/front/magneton.pic \
  pokemon/back_sw/magnetonb.pic \
  pokemon/front/primeape.pic \
  pokemon/back_sw/primeapeb.pic \
  pokemon/front/nidoranm.pic \
  pokemon/back_sw/nidoranmb.pic \
  pokemon/front/voltorb.pic

check_section "Pics 3" \
  pokemon/front/articuno.pic \
  pokemon/back_sw/articunob.pic \
  pokemon/front/zapdos.pic \
  pokemon/back_sw/zapdosb.pic \
  pokemon/front_alt/zapdos.pic \
  pokemon/front/ditto.pic \
  pokemon/back_sw/dittob.pic \
  pokemon/front/meowth.pic \
  pokemon/back_sw/meowthb.pic \
  pokemon/front/krabby.pic \
  pokemon/back_sw/krabbyb.pic \
  pokemon/front/vulpix.pic \
  pokemon/back_sw/vulpixb.pic \
  pokemon/front/ninetales.pic \
  pokemon/back_sw/ninetalesb.pic \
  pokemon/front/pikachu.pic \
  pokemon/back_sw/pikachub.pic \
  pokemon/front/raichu.pic \
  pokemon/back_sw/raichub.pic \
  pokemon/front/dratini.pic \
  pokemon/back_sw/dratinib.pic \
  pokemon/front/kabuto.pic \
  pokemon/back_sw/kabutob.pic \
  pokemon/front/kabutops.pic \
  pokemon/back_sw/kabutopsb.pic \
  pokemon/front/seadra.pic \
  pokemon/back_sw/seadrab.pic \
  pokemon/front/sandshrew.pic \
  pokemon/back_sw/sandshrewb.pic \
  pokemon/front/sandslash.pic \
  pokemon/back_sw/sandslashb.pic \
  pokemon/front/omanyte.pic \
  pokemon/back_sw/omanyteb.pic \
  pokemon/front/omastar.pic \
  pokemon/back_sw/omastarb.pic \
  pokemon/front/jigglypuff.pic \
  pokemon/back_sw/jigglypuffb.pic \
  pokemon/front/wigglytuff.pic \
  pokemon/back_sw/wigglytuffb.pic \
  pokemon/front/beedrill.pic \
  pokemon/back_sw/beedrillb.pic \
  pokemon/back_sw/exeggutorb.pic \
  pokemon/front_alt/exeggutor.pic \
  pokemon/front/dewgong.pic \
  pokemon/back_sw/dewgongb.pic \
  pokemon/front/zubat.pic \
  pokemon/back_sw/zubatb.pic \
  pokemon/back_sw/psyduckb.pic \
  pokemon/back_sw/rattatab.pic
 
check_section "Pics 4" \
  pokemon/front/dodrio.pic \
  pokemon/back_sw/dodriob.pic \
  pokemon/front/dugtrio.pic \
  pokemon/back_sw/dugtriob.pic \
  pokemon/front/venomoth.pic \
  pokemon/back_sw/venomothb.pic \
  pokemon/front/caterpie.pic \
  pokemon/back_sw/caterpieb.pic \
  pokemon/front/butterfree.pic \
  pokemon/back_sw/butterfreeb.pic \
  pokemon/front_alt/butterfree.pic \
  pokemon/front/machamp.pic \
  pokemon/back_sw/machampb.pic \
  pokemon/front/golduck.pic \
  pokemon/back_sw/golduckb.pic \
  pokemon/front/hypno.pic \
  pokemon/back_sw/hypnob.pic \
  pokemon/front/golbat.pic \
  pokemon/back_sw/golbatb.pic \
  pokemon/front_alt/golbat.pic \
  pokemon/front/mewtwo.pic \
  pokemon/back_sw/mewtwob.pic \
  pokemon/front_alt/mewtwo.pic \
  pokemon/front/snorlax.pic \
  pokemon/back_sw/snorlaxb.pic \
  pokemon/front/magikarp.pic \
  pokemon/back_sw/magikarpb.pic \
  pokemon/front/kingler.pic \
  pokemon/back_sw/kinglerb.pic \
  pokemon/front/electrode.pic \
  pokemon/back_sw/electrodeb.pic \
  pokemon/front/clefable.pic \
  pokemon/back_sw/clefableb.pic \
  pokemon/front/goldeen.pic \
  pokemon/back_sw/goldeenb.pic \
  pokemon/front/magnemite.pic \
  pokemon/back_sw/magnemiteb.pic \
  pokemon/front/metapod.pic \
  pokemon/back_sw/metapodb.pic \
  pokemon/front/hitmonchan.pic \
  pokemon/back_sw/pinsirb.pic \
  pokemon/front/charmeleon.pic \
  pokemon/back_sw/charmeleonb.pic \
  player/redb.pic \
  battle/oldmanb.pic \
  player/redb_big.pic \
  battle/oldmanb_big.pic \
  pokemon/back/persianb.pic \
  pokemon/back/starmieb.pic \
  pokemon/back/victreebelb.pic \
  pokemon/back/pidgeotb.pic

check_section "Pics 5" \
  pokemon/front/bulbasaur.pic \
  pokemon/back_sw/bulbasaurb.pic \
  pokemon/front_alt/bulbasaur.pic \
  pokemon/front/venusaur.pic \
  pokemon/back_sw/venusaurb.pic \
  pokemon/front/seaking.pic \
  pokemon/back_sw/seakingb.pic \
  pokemon/front/ponyta.pic \
  pokemon/back_sw/ponytab.pic \
  pokemon/front/rapidash.pic \
  pokemon/back_sw/rapidashb.pic \
  pokemon/front/raticate.pic \
  pokemon/back_sw/raticateb.pic \
  pokemon/front_alt/raticate.pic \
  pokemon/front/nidorino.pic \
  pokemon/back_sw/nidorinob.pic \
  pokemon/front_alt/nidorino.pic \
  pokemon/front/nidorina.pic \
  pokemon/back_sw/nidorinab.pic \
  pokemon/front/geodude.pic \
  pokemon/back_sw/geodudeb.pic \
  pokemon/front/porygon.pic \
  pokemon/back_sw/porygonb.pic \
  pokemon/front/aerodactyl.pic \
  pokemon/back_sw/aerodactylb.pic \
  pokemon/front/charmander.pic \
  pokemon/back_sw/charmanderb.pic \
  pokemon/front/wartortle.pic \
  pokemon/back_sw/wartortleb.pic \
  pokemon/front/charizard.pic \
  pokemon/back_sw/charizardb.pic \
  pokemon/front/cloyster.pic \
  pokemon/back_sw/cloysterb.pic \
  pokemon/front_alt/cloyster.pic \
  pokemon/front/pinsir.pic \
  pokemon/back_sw/hitmonchanb.pic \
  pokemon/front_alt/pinsir.pic \
  pokemon/front/tentacruel.pic \
  pokemon/back_sw/tentacruelb.pic \
  pokemon/front_alt/tentacruel.pic \
  pokemon/front/starmie.pic \
  pokemon/back_sw/starmieb.pic \
  pokemon/front_alt/starmie.pic \
  pokemon/front/rattata.pic \
  pokemon/front/horsea.pic \
  pokemon/back_sw/horseab.pic \
  pokemon/back/eeveeb.pic

check_section "Pics 6" \
  trainers/youngster.pic \
  trainers/bugcatcher.pic \
  trainers/lass.pic \
  trainers/sailor.pic \
  trainers/jr.trainerm.pic \
  trainers/jr.trainerf.pic \
  trainers/pokemaniac.pic \
  trainers/supernerd.pic \
  trainers/hiker.pic \
  trainers/biker.pic \
  trainers/burglar.pic \
  trainers/engineer.pic \
  trainers/fisher.pic \
  trainers/swimmer.pic \
  trainers/cueball.pic \
  trainers/gambler.pic \
  trainers/beauty.pic \
  trainers/psychic.pic \
  trainers/rocker.pic \
  trainers/juggler.pic \
  trainers/tamer.pic \
  trainers/birdkeeper.pic \
  trainers/blackbelt.pic \
  trainers/rival1.pic \
  trainers/prof.oak.pic \
  trainers/scientist.pic \
  trainers/giovanni.pic \
  trainers/rocket.pic \
  trainers/cooltrainerm.pic \
  trainers/cooltrainerf.pic \
  trainers/bruno.pic \
  trainers/brock.pic \
  trainers/misty.pic \
  trainers/lt.surge.pic \
  trainers/erika.pic \
  trainers/koga.pic \
  trainers/blaine.pic \
  trainers/sabrina.pic \
  trainers/gentleman.pic \
  trainers/rival2.pic \
  trainers/rival3.pic \
  trainers/lorelei.pic \
  trainers/channeler.pic \
  trainers/agatha.pic \
  trainers/lance.pic \
  pokemon/front/mew.pic \
  pokemon/back_sw/mewb.pic \
  pokemon/back/pidgeottob.pic

check_section "Pics 7" \
  pokemon/front/shellder.pic \
  pokemon/back_sw/shellderb.pic \
  pokemon/front/tentacool.pic \
  pokemon/back_sw/tentacoolb.pic \
  pokemon/front/gastly.pic \
  pokemon/back_sw/gastlyb.pic \
  pokemon/front/scyther.pic \
  pokemon/front/staryu.pic \
  pokemon/back_sw/staryub.pic \
  pokemon/front/blastoise.pic \
  pokemon/front_alt/blastoise.pic \
  pokemon/back_sw/blastoiseb.pic \
  pokemon/front/mankey.pic \
  pokemon/back_sw/mankeyb.pic \
  pokemon/front_alt/mankey.pic \
  pokemon/front/seel.pic \
  pokemon/back_sw/seelb.pic \
  pokemon/front/diglett.pic \
  pokemon/back_sw/diglettb.pic \
  pokemon/front/tauros.pic \
  pokemon/back_sw/taurosb.pic \
  pokemon/front/farfetchd.pic \
  pokemon/back_sw/farfetchdb.pic \
  pokemon/front/venonat.pic \
  pokemon/front/dragonite.pic \
  pokemon/back_sw/dragoniteb.pic \
  pokemon/front/doduo.pic \
  pokemon/back_sw/doduob.pic \
  pokemon/front/poliwag.pic \
  pokemon/back_sw/poliwagb.pic \
  pokemon/front/jynx.pic \
  pokemon/back_sw/jynxb.pic \
  pokemon/front/moltres.pic \
  pokemon/back_sw/moltresb.pic \
  pokemon/front/tangela.pic \
  pokemon/back_sw/tangelab.pic \
  pokemon/front/eevee.pic \
  pokemon/back_sw/eeveeb.pic \
  pokemon/front/flareon.pic \
  pokemon/back_sw/flareonb.pic \
  pokemon/front/jolteon.pic \
  pokemon/back_sw/jolteonb.pic \
  pokemon/front/vaporeon.pic \
  pokemon/back_sw/vaporeonb.pic \
  pokemon/front/muk.pic \
  pokemon/back_sw/mukb.pic \
  pokemon/back/jolteonb.pic \
  pokemon/back_sw/dragonairb.pic

check_section "Pics 8" \
  pokemon/front/machop.pic \
  pokemon/back_sw/machopb.pic \
  pokemon/front_alt/machop.pic \
  pokemon/front/ekans.pic \
  pokemon/back_sw/ekansb.pic \
  pokemon/front/paras.pic \
  pokemon/back_sw/parasb.pic \
  pokemon/front/poliwhirl.pic \
  pokemon/back_sw/poliwhirlb.pic \
  pokemon/front/poliwrath.pic \
  pokemon/back_sw/poliwrathb.pic \
  pokemon/front/weedle.pic \
  pokemon/back_sw/weedleb.pic \
  pokemon/front/weezing.pic \
  pokemon/back_sw/weezingb.pic \
  pokemon/front/persian.pic \
  pokemon/back_sw/persianb.pic \
  pokemon/front/marowak.pic \
  pokemon/back_sw/marowakb.pic \
  pokemon/front/haunter.pic \
  pokemon/back_sw/haunterb.pic \
  pokemon/front/abra.pic \
  pokemon/back_sw/abrab.pic \
  pokemon/front_alt/abra.pic \
  pokemon/front/alakazam.pic \
  pokemon/back_sw/alakazamb.pic \
  pokemon/front/pidgeotto.pic \
  pokemon/back_sw/pidgeottob.pic \
  pokemon/front_alt/pidgeotto.pic \
  pokemon/front/pidgeot.pic \
  pokemon/back_sw/pidgeotb.pic \
  pokemon/front_alt/pidgeot.pic \
  pokemon/front/oddish.pic \
  pokemon/back_sw/oddishb.pic \
  pokemon/front/gloom.pic \
  pokemon/back_sw/gloomb.pic \
  pokemon/front/vileplume.pic \
  pokemon/back_sw/vileplumeb.pic \
  pokemon/front/bellsprout.pic \
  pokemon/back_sw/bellsproutb.pic \
  pokemon/front/weepinbell.pic \
  pokemon/back_sw/weepinbellb.pic \
  pokemon/front/victreebel.pic \
  pokemon/back_sw/victreebelb.pic \
  pokemon/front/dragonair.pic \
  pokemon/back_sw/scytherb.pic \
  pokemon/front/missingno.pic \
  pokemon/back_sw/missingnob.pic \
  pokemon/back/missingnob.pic \
  pokemon/front/fossilaerodactyl.pic \
  pokemon/front/fossilkabutops.pic \
  battle/ghost.pic

check_section "Pics 9" \
  pokemon/back/rhydonb.pic \
  pokemon/back/kangaskhanb.pic \
  pokemon/back/nidoranmb.pic \
  pokemon/back/clefairyb.pic \
  pokemon/back/spearowb.pic \
  pokemon/back/voltorbb.pic \
  pokemon/back/nidokingb.pic \
  pokemon/back/slowbrob.pic \
  pokemon/back/ivysaurb.pic \
  pokemon/back/exeggutorb.pic \
  pokemon/back/lickitungb.pic \
  pokemon/back/exeggcuteb.pic \
  pokemon/back/grimerb.pic \
  pokemon/back/gengarb.pic \
  pokemon/back/nidoranfb.pic \
  pokemon/back/nidoqueenb.pic \
  pokemon/back/cuboneb.pic \
  pokemon/back/rhyhornb.pic \
  pokemon/back/laprasb.pic \
  pokemon/back/arcanineb.pic \
  pokemon/back/gyaradosb.pic \
  pokemon/back/growlitheb.pic \
  pokemon/back/onixb.pic \
  pokemon/back/fearowb.pic \
  pokemon/back/pidgeyb.pic \
  pokemon/back/slowpokeb.pic \
  pokemon/back/kadabrab.pic \
  pokemon/back/gravelerb.pic \
  pokemon/back/chanseyb.pic \
  pokemon/back/machokeb.pic \
  pokemon/back/mr.mimeb.pic \
  pokemon/back/hitmonleeb.pic \
  pokemon/back/hitmonchanb.pic \
  pokemon/back/arbokb.pic \
  pokemon/back/parasectb.pic \
  pokemon/back/psyduckb.pic \
  pokemon/back/drowzeeb.pic \
  pokemon/back/golemb.pic \
  pokemon/back/magmarb.pic \
  pokemon/back/electabuzzb.pic \
  pokemon/back/magnetonb.pic \
  pokemon/back/koffingb.pic \
  pokemon/back/articunob.pic \
  pokemon/back/zapdosb.pic \
  pokemon/back/dittob.pic \
  pokemon/back/meowthb.pic \
  pokemon/back/krabbyb.pic \
  pokemon/back/vulpixb.pic \
  pokemon/back/ninetalesb.pic \
  pokemon/back/pikachub.pic \
  pokemon/back/raichub.pic \
  pokemon/back/dratinib.pic \
  pokemon/back/dragonairb.pic \
  pokemon/back/kabutob.pic \
  pokemon/back/kabutopsb.pic \
  pokemon/back/horseab.pic \
  pokemon/back/seadrab.pic \
  pokemon/back/sandshrewb.pic \
  pokemon/back/sandslashb.pic \
  pokemon/back/omanyteb.pic \
  pokemon/back/omastarb.pic \
  pokemon/back/jigglypuffb.pic \
  pokemon/back/wigglytuffb.pic \
  pokemon/back/beedrillb.pic \
  pokemon/back/kakunab.pic \
  pokemon/back/dodriob.pic \
  pokemon/back/primeapeb.pic \
  pokemon/back/dugtriob.pic \
  pokemon/back/venomothb.pic \
  pokemon/back/dewgongb.pic \
  pokemon/back/caterpieb.pic \
  pokemon/back/metapodb.pic \
  pokemon/back/butterfreeb.pic \
  pokemon/back/machampb.pic \
  pokemon/back/golduckb.pic \
  pokemon/back/hypnob.pic \
  pokemon/back/golbatb.pic \
  pokemon/back/mewtwob.pic \
  pokemon/back/snorlaxb.pic \
  pokemon/back/magikarpb.pic \
  pokemon/back/mukb.pic \
  pokemon/back/kinglerb.pic \
  pokemon/back/cloysterb.pic \
  pokemon/back/electrodeb.pic \
  pokemon/back/clefableb.pic \
  pokemon/back/bulbasaurb.pic \
  pokemon/back/venusaurb.pic \
  pokemon/back/tentacruelb.pic \
  pokemon/back/goldeenb.pic \
  pokemon/back/seakingb.pic \
  pokemon/back/ponytab.pic \
  pokemon/back/rapidashb.pic \
  pokemon/back/rattatab.pic \
  pokemon/back/raticateb.pic \
  pokemon/back/nidorinob.pic \
  pokemon/back/nidorinab.pic \
  pokemon/back/geodudeb.pic \
  pokemon/back/porygonb.pic \
  pokemon/back/aerodactylb.pic \
  pokemon/back/magnemiteb.pic \
  pokemon/back/charmanderb.pic \
  pokemon/back/squirtleb.pic \
  pokemon/back/charmeleonb.pic \
  pokemon/back/wartortleb.pic \
  pokemon/back/charizardb.pic \
  pokemon/back/shellderb.pic \
  pokemon/back/tentacoolb.pic \
  pokemon/back/gastlyb.pic \
  pokemon/back/scytherb.pic \
  pokemon/back/staryub.pic \
  pokemon/back/blastoiseb.pic \
  pokemon/back/mankeyb.pic \
  pokemon/back/seelb.pic \
  pokemon/back/diglettb.pic \
  pokemon/back/taurosb.pic \
  pokemon/back/farfetchdb.pic \
  pokemon/back/venonatb.pic \
  pokemon/back/dragoniteb.pic \
  pokemon/back/doduob.pic \
  pokemon/back/poliwagb.pic \
  pokemon/back/jynxb.pic \
  pokemon/back/moltresb.pic \
  pokemon/back/pinsirb.pic \
  pokemon/back/tangelab.pic

check_section "Pics 10" \
  pokemon/back/flareonb.pic \
  pokemon/back/vaporeonb.pic \
  pokemon/back/zubatb.pic \
  pokemon/back/ekansb.pic \
  pokemon/back/parasb.pic \
  pokemon/back/poliwhirlb.pic \
  pokemon/back/poliwrathb.pic \
  pokemon/back/weedleb.pic \
  pokemon/back/weezingb.pic \
  pokemon/back/marowakb.pic \
  pokemon/back/haunterb.pic \
  pokemon/back/abrab.pic \
  pokemon/back/alakazamb.pic \
  pokemon/back/bellsproutb.pic \
  pokemon/back/weepinbellb.pic \
  pokemon/back/oddishb.pic \
  pokemon/back/gloomb.pic \
  pokemon/back/vileplumeb.pic \
  pokemon/back/armored_mewtwob.pic \
  pokemon/front_alt/articuno.pic \
  pokemon/back_sw/venonatb.pic \
  pokemon/front/koffing.pic \
  pokemon/back_sw/koffingb.pic \
  pokemon/front_alt/koffing.pic \
  pokemon/front/armored_mewtwo.pic \
  pokemon/back_sw/armored_mewtwob.pic \
  pokemon/front_alt/armored_mewtwo.pic \
  pokemon/back_sw/winter_dragonairb.pic \
  pokemon/back/volcanic_magmarb.pic \
  pokemon/back/winter_dragonairb.pic \
  unused_prototype_sprites/cool_kid.pic \
  unused_prototype_sprites/firefighter.pic \
  unused_prototype_sprites/ranger.pic \
  trainers/rangerf.pic \
  unused_prototype_sprites/rookie.pic \
  unused_prototype_sprites/soldier.pic \
  unused_prototype_sprites/chief.pic \
  unused_prototype_sprites/gym_guide.pic \
  unused_prototype_sprites/fitness_girl.pic \
  unused_prototype_sprites/sprinter.pic \
  unused_prototype_sprites/fist_fighter.pic

check_section "Pics 11" \
  pokemon/front_alt/jynx.pic \
  pokemon/front_alt/farfetchd.pic \
  pokemon/front_alt/omanyte.pic \
  pokemon/front_alt/spearow.pic \
  pokemon/front_alt/scyther.pic \
  pokemon/front_alt/golduck.pic \
  pokemon/front_alt/dragonair.pic \
  pokemon/front_alt/volcanic_magmar.pic \
  pokemon/back_sw/volcanic_magmarb.pic \
  pokemon/front_alt/exeggutor.pic \
  pokemon/back/mewb.pic \
  battle/spirit_torched.pic \
  battle/spirit_chunky.pic \
  battle/spirit_painless.pic \
  battle/spirit_irradiated.pic \
  battle/spirit_the_maw.pic \
  player/lava_suitb_big.pic \
  player/lava_suitb.pic \
  player/scuba_suitb_big.pic \
  player/scuba_suitb.pic
